<i><h3>*-----ASSUMING THAT THE FORWARD PROPAGATION HAS ALREADY HAPPENED-----*</h3><br/>
<b>BACK-PROP</b> :
<i>
<b>MAIN TASK</b> :<li>
    <ol>How to learn multiple layers of features ?</ol>
    <ol>How to learn weights of hidden units? [They are called hidden units for a reason]</ol>
</li>


<i><b>OTHER WAYS TO DO IT AND WHY BACKPROPAGATION IS A BETTER WAY</b></i>
1.<h4> Perturb weights manually , and then check the output . See how well they fare against their respective target</h4><br/>
<b>Problem</b>  :<b>TOO INEFFICIENT</b> .<br/>As the number of neurons/layers increase the ways of Perturbing a weight is increased rapidly . for a 2 hidden layer network ,with 4 neurons each it would take 
*input_size*4*4*output_size* number of ways to get it right 

<h5>and even to get this going </h5>: 
<i>There is a necessity to have a loop that does the task of changing the features without looking into the task</i>
<i>without trial and error .automated one ofcourse.</i>



<h3>ADVANTAGES OF USING BACK_PROPAGATION</h3>:
    1. No need to know what hidden units are doing . Instead of using desired activations to train hidden units use derivatives with-respect-to hidden activities
    2. Each activation can have  different effects on different output units* 
    3. error derivatives tells how fast error changes with respect to the hidden activity

<img src="eins.jpeg" width="400" height="1000"  >

<img src="loss.jpeg" width=400 height=1000><h3>A loss function contain </h3>
<h3>y<sub>j,c</sub> the output and t<sub>j,c</sub> the target</h3>

<img src="sigmoid.jpeg" width=400 height=1000><h2>And a sigmoid activation function </h2>:<br/><b> This function just gives out the squashed value of an input such that the ouput lies between 0 and 1 </b>

<img src="work.jpeg" width=400 height=1000><h3>The work of backprop goes something like this  making use of the chain rule  ,which gives the correspondance</h3>

<h4>STEPS</h4>

<h4>STEP 1</h4><i>Convert the discrepancy between each operation and its target value into an error derivative</i><br></br>
<h4>STEP 2</h4><i>Compute error derivatives in each hidden layer from error derivatives from the layer before [or above ]</i>


<i>The above steps has to go on from the output and then end at the input of the network layer</i> <br></br>


<h5>This will be implemented in the following way</h5>
       <i> At every neuron there will be two operations going on .<br> 1. Calculation of local gradient and calculation of the external gradient <br>2.Multiplying the gradients from the upper layers and distributing the gradients<br>
<b>Local gradient </b>: Are those which are the inputs to that particular neuron . As and when the neuron gets the input it calculates the local gradient<br>
<b>external gradient</b>: Are those gradients that are obtained by the upper layer neurons  ,which they get by multiplying a output_value and calculating its gradient and multiplying it with the local derivatives in the neuron itself . 
<br><br>
local gradients are <b>JACOBIAN MATRICES</b><br>
external gradients are <b>VECTORS</b>

In [1]:
import torch
import numpy as np

In [2]:
torch.__version__

'1.1.0.dev20190517'

In [7]:
a = torch.rand(3,3)

In [8]:
a

tensor([[5.5972e-01, 5.0503e-01, 3.2164e-01],
        [6.3807e-04, 7.2887e-01, 5.2593e-02],
        [1.6526e-01, 5.3888e-01, 6.6202e-01]])

In [9]:
b = torch.rand_like(a , requires_grad=True)

*in torch specification has to be made whether to have the gradient calculated during backprop or not that is done by giving a boolean value to requires_grad*


In [10]:
b

tensor([[0.8815, 0.4754, 0.1780],
        [0.7745, 0.7840, 0.9789],
        [0.7123, 0.1485, 0.1391]], requires_grad=True)

In [11]:
x = a+b

In [14]:
x.requires_grad

True

In [45]:
import torch.nn as nn
x = torch.randn(10 ,3)
y = torch.randn(10 , 2)

linear = nn.Linear(3,2)

print(linear.bias)
print(linear.weight)
criterion = nn.MSELoss()
optimiser = torch.optim.RMSprop(linear.parameters() , lr=0.01)

pred = linear(x)
loss= criterion(pred , y)
#USAGE OF .item() is needed because loss is a tensor and to get the individual value in it .
print('loss: ' , loss.item())
print('1' if  loss.grad_fn.requires_grad==True else '0')
loss.backward()#Does the backpropagation 


optimiser.zero_grad()
optimiser.step()#updates 
pred = linear(x)
loss = criterion(pred ,y)
print('loss after 1 step optimisation ', loss.item())

Parameter containing:
tensor([-0.1626,  0.0620], requires_grad=True)
Parameter containing:
tensor([[-0.0822, -0.2454,  0.1748],
        [ 0.1505, -0.5158,  0.5427]], requires_grad=True)
loss:  0.8906837701797485
1
loss after 1 step optimisation  0.8906837701797485
